### ISSUE TITLE
User should be able to config the locations of intermediate and output files

### ISSUE THREAD

**Issue by wshanshan** [datakind/dk-routing#25]
It's common to run different scenarios, therefore, it's critical for users to have controls on the output file folders. 

There are some issues about how the output files are stored: 

1. build_time_dist_matrix.process_nodes(...) 
Location for the output files can not be configured. They will always be created in /data/gps_data_clean, and /data/time_and_dist_matrices/. 

2. optimization.main(...)
Although the function has a parameter 'output_dir', solution.txt will already be created in '.',  manual_routes_edits.xlsx, manual_vehicles.csv, clean_gps_points.csv will be created in 'manual_edits'. regardless the setting of 'output_dir'. If the folder 'manual_edits' does not exist, the function will fail

3. visualization.main(...)
Although the function has a parameter 'output_dir', route_geojson.geojson and node_geojson.geojson are always created in '.' regardless the parameter 'output_dir', html files will be created in folder 'maps' regardless the setting of 'output_dir'

**Comment by Zebreu** [comment]
Should be done as of PR 6
