### ISSUE TITLE
wget: missing URL Usage: wget [OPTION]... [URL]...

### ISSUE THREAD

**Issue by kashivirus** [datakind/dk-routing#33]
Step 10/52 : RUN wget --no-check-certificate $osm_download_url
 ---> Running in 09d05ad32c29
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

**Comment by Zebreu** [comment]
You didn't indicate which script you ran, but if you tried to do a simple docker build as is, it's missing arguments and probably would produce this error. 

https://github.com/datakind/dk-routing/blob/main/dkroutingtool/create_application_after_config.sh provides an URL

**Comment by kashivirus** [comment]
i ran this one sh s_build_docker_dev.sh

**Comment by Zebreu** [comment]
You'll need yq to parse the url and the build should work on Linux but may not on any other OS. In any case, you can make sure that the environment variable (osm_download_url) is properly parsed from build_parameters.yml or if that still doesn't work, you can modify the lines in the Dockerfile so they're hard coded for your use.
